### ISSUE TITLE
Kde je zadání projektu?

### ISSUE THREAD

**Issue by Richard004** [Richard004/znamkamarada#1]
Pokud někdo má dokumenty k zadání, tak je prosím připojte.

**Comment by Richard004** [comment]
Tak zatím vím pouze o té smlouvě, která je ke stažení zde.
https://smlouvy.gov.cz/smlouva/soubor/14774020/SMLOUVA_IS-EDAZ_REDIGOV%C3%81NO.PDF

**Comment by Richard004** [comment]
Dále tu máme schémátko:
![image](https://user-images.githubusercontent.com/8113705/72671425-51a54d00-3a4a-11ea-8b5f-01527e0fe557.png)

**Comment by MichalKalita** [comment]
V tom schématu to přímo není, respektive možná se to skrývá za "statistikami" z kamer. 

Ale v zájmu PČR je zaznamenávat a na dlouhou dobu uchovávat provoz všech aut. PČR zadá SPZ a vypadne jim kde bylo auto za posledních 10let.

**Comment by Richard004** [comment]
Velmi dobře. 10 let * počet kamer * intenzita provozu dává alespoň nějakou představu o tom, jak nadimenzovat archiv. Je to jeden z těch požadavků který jsem v zásadě očekával a je dobře že jej vedeme v patrnosti.
